### ISSUE TITLE
add "xxxxxx" industry

### ISSUE THREAD

**Issue by sebastianovide** [Geovation/security-framework#2]
need to define the industry "xxxxxx" and change the title of this.

**acceptance criteria**
- [x] find a company for which the software returns "not implemented"
- [x] define what "xxxxxx" is
- [x] the industry "xxxxxx" is covered by the software
- [x] documenting how "xxxxxxx" is taken into consideration in the formula (git MD format)

**as usual before moving to _test/merge_** 
- [ ] pull request
- [ ] runnable demo so that tester can execute in their own machine.

**before moving it to _done_**
- [ ] tested
- [ ] code reviewed and merged

**Comment by sebastianovide** [comment]
I cannot see it in a live env

**Comment by abellj01** [comment]
I have implemented a case for company that works for eg "True mile"
Industry: Online services
Covered by software: Yes

**Comment by abellj01** [comment]
I have implemented a case for company such as "Trumyle"
Industry: Online services
Covered by software: Yes with new if clause
Documentation: No formula

**Comment by abellj01** [comment]
I reopened because I realised that it had to be merged and then tested by You before moving to done.
